spring:
  application:
    name: blog-user-service
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost/blog_users
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
      show-sql: true
      generate-ddl: true
    sql:
      init:
        mode: always
server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost